class TestModifyModel:
    def test_biject_variable(self): ...
    def test_rename_variable(self): ...
    def test_change_per_obs_of_a_dist(self): ...
    def test_change_parameter_flag_of_a_var(self): ...
    def test_change_obs_flag_of_a_var(self): ...

    def test_node_add_inputs(self): ...
    def test_node_set_inputs(self): ...

    def test_bracket_replace_value_input_var_with_var(self): ...

    def test_bracket_replace_value_input_var_with_var_that_has_model(self): ...
    def test_bracket_replace_value_input_var_with_var_in_same_model(self): ...

    def test_bracket_replace_value_input_var_with_node(self): ...
    def test_bracket_replace_value_input_var_with_array(self): ...

    def test_bracket_replace_log_prob_input_var_with_var(self): ...
    def test_bracket_replace_log_prob_input_var_with_node(self): ...
    def test_bracket_replace_log_prob_input_var_with_array(self): ...

    def test_replace_var_with_var(self): ...
    def test_replace_var_with_var_that_has_model(self): ...
    def test_replace_var_with_var_in_same_model(self): ...
    def test_replace_var_with_node(self): ...
    def test_replace_var_with_array(self): ...

    def test_disconnected_parents_of_replaced_var_are_removed(self): ...
    def test_connected_parents_of_replaced_var_are_kept(self): ...

    def test_singleton_node_is_dropped(self): ...
    def test_singleton_var_is_not_dropped(self): ...
    def test_singleton_var_is_explicitly_dropped(self): ...
