name: Docs
on: [push]

jobs:
  notebooks:
    name: "Build tutorials and trigger documentation build"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.2"

      - name: Install pre-compiled R packages from Ubuntu repository
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends r-cran-tidyverse
          sudo apt-get install -y graphviz graphviz-dev

      - name: Set R library paths
        run: echo "R_LIBS_USER=/home/runner/work/_temp/Library:/usr/lib/R/site-library" >> $GITHUB_ENV

      - name: Install additional R packages
        shell: Rscript {0}
        run: |
          install.packages('VGAM')
          install.packages('MASS')

      - name: Install rliesel
        shell: Rscript {0}
        run: |
          remotes::install_github('liesel-devs/rliesel', auth_token='${{ secrets.GITHUB_TOKEN }}')

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install .[dev]
          python -m pip install pygraphviz
          pip list

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render tutorials
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: docs/source/tutorials/qmd

      - uses: actions/upload-artifact@v3
        with:
          name: tutorials-for-${{ github.sha }}
          path: docs/source/tutorials/md

      - name: Trigger RTDs build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
