name: Docs
on: [pull_request]

jobs:
  notebooks:
    name: "Build the tutorials for the docs"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -e .[dev]
          pip list

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.2"
        run: Rscript -e "print('R installed')"

      - name: Install R packages
        run: |
          Rscript -e "install.packages('tidyverse')"
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_github('liesel-devs/rliesel')"
          Rscript -e "install.packages('VGAM')"
          Rscript -e "install.packages('reticulate')"
          Rscript -e "install.packages('MASS')"

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render tutorials
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: docs/source/tutorials

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: tutorials-for-${{ github.sha }}
      #     path: docs/source/tutorials/md

      # - name: Trigger RTDs build
      #   uses: dfm/rtds-action@v1
      #   with:
      #     webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
      #     webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
      #     commit_ref: ${{ github.ref }}
