name: doctest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  doctest:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v4


      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install liesel
        run: uv sync --locked --dev --group pymc

      - name: Run pytest
        run: uv run pytest --doctest-modules src/liesel
