name: pdoc

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install liesel
        run: |
          pip install .[dev]
          pip list

      - name: Run pdoc
        run: pdoc -o ./docs -t ./misc/pdoc-template liesel

      - name: Upload artifact
        run: tar -hcf ./artifact.tar --directory ./docs .
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ./artifact.tar

  deploy:
      needs: build
      runs-on: ubuntu-latest
      timeout-minutes: 10

      permissions:
        pages: write
        id-token: write

      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

      steps:
        - name: Deploy pages
          uses: actions/deploy-pages@v1
