name: pytest-pull

on:
  pull_request:
    branches: [main]

jobs:
  pytest-pull:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install liesel
        run: |
          pip install .[dev]
          pip list

      - name: Run pytest
        run: pytest --run-mcmc
