name: pytest-pull

on:
  pull_request:
    branches: [main]

jobs:
  pytest-pull:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      # - name: Cache pip
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml', '**/setup.py', '**/requirements*.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-${{ matrix.python-version }}-

      - name: Install liesel
        run: uv sync --locked --dev

      - name: Run pytest
        run: uv run pytest --run-mcmc
