name: pytest

on:
  push:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install liesel
        run: |
          pip install .[dev]
          pip list

      - name: Run pytest
        run: pytest --cov=liesel --run-mcmc
