name: pytest-pull

on:
  pull_request:
    branches: [main]

jobs:
  pytest-pull:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install liesel
        run: |
          pip install .[dev]
          pip list

      - name: Run pytest
        run: pytest --run-mcmc
